trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  rgName: rg-204-pipelines
  location: westeurope
  templateFilePath: ./Templates/infrastructure.bicep
  appName: thepipelineapp
  env: test

steps:
- script: echo 'Hello there!!!!!!'
- task: AzureCLI@2
  displayName: Create Resource Group
  inputs:
    azureSubscription: 'thenotstupedconnection'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: az group create --name $(rgName) --location $(location)
- task: AzureCLI@2
  displayName: Create Infrastructure
  inputs:
    azureSubscription: 'thenotstupedconnection'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: az deployment group create --resource-group $(rgName) --template-file $(templateFilePath) --parameters appName=$(appName) --parameters env=$(env)
